/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.VPuntos;
import control.controlador;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import Excepciones.ResultadoPartido;
/**
 *
 * @author 1gdaw02
 */
public class VPuntos extends javax.swing.JFrame {
static boolean yes = false;
    /**
     * Creates new form VPuntos
     */
    public VPuntos() {
        yes = false;
        initComponents();
        initIcon();
        setLocationRelativeTo(null);
        cbLiga.addItem("-- Seleccione una liga --");
        controlador.llenarLiga(cbLiga);
        yes = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbLiga = new javax.swing.JComboBox<>();
        cbJornadas = new javax.swing.JComboBox<>();
        cbPartidos = new javax.swing.JComboBox<>();
        tfe2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfe1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        le1 = new javax.swing.JLabel();
        le2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Clasificacion");

        cbLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLigaActionPerformed(evt);
            }
        });

        cbJornadas.setEnabled(false);
        cbJornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJornadasActionPerformed(evt);
            }
        });

        cbPartidos.setEnabled(false);
        cbPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPartidosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("-");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Resultado");

        le1.setForeground(new java.awt.Color(0, 0, 0));
        le1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        le2.setForeground(new java.awt.Color(0, 0, 0));
        le2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cbLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(cbJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(le2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfe2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(cbPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(le1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(tfe1))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(171, 171, 171)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(le1)
                    .addComponent(le2))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLigaActionPerformed
        // TODO add your handling code here:
        if(yes){
            yes = false;
            cbJornadas.removeAllItems();
            cbJornadas.addItem("-- Seleccione una jornada --");
            cbJornadas.setEnabled(true);
            controlador.llenarJornadas((String)cbLiga.getSelectedItem(),cbJornadas);
            yes = true;
        }
    }//GEN-LAST:event_cbLigaActionPerformed

    private void cbJornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJornadasActionPerformed
        // TODO add your handling code here:
        try{
            if(yes){
                yes = false;
                cbPartidos.removeAllItems();
                cbPartidos.addItem("-- Seleccione un partido --");
                cbPartidos.setEnabled(true);
                controlador.llenarPartidos((String)cbJornadas.getSelectedItem(),cbPartidos);
                yes = true;
            }
        }catch (Exception e){
            System.out.println("Parse exception");
        }
    }//GEN-LAST:event_cbJornadasActionPerformed

    private void cbPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPartidosActionPerformed
        // TODO add your handling code here:
        if(yes){
            yes = false;           
            controlador.llenarTfPartido(cbPartidos.getSelectedIndex());           
            le1.setText(controlador.le1());
            le2.setText(controlador.le2());            
            yes = true;
        }
    }//GEN-LAST:event_cbPartidosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String resultado;
            if(validar()){
                if(Integer.parseInt(tfe1.getText())>Integer.parseInt(tfe2.getText())){
                    controlador.resultado(le1.getText(), null);
                    resultado=tfe1.getText()+"-"+tfe2.getText();
                    controlador.resultadoPartido(le1.getText(), resultado, false);
                }else
                    if(Integer.parseInt(tfe2.getText())>Integer.parseInt(tfe1.getText())){
                        controlador.resultado(null, le2.getText());
                        resultado=tfe1.getText()+"-"+tfe2.getText();
                        controlador.resultadoPartido(le2.getText(), resultado, false);
                    }else
                        if(Integer.parseInt(tfe2.getText())==Integer.parseInt(tfe1.getText())){
                            controlador.resultado(le1.getText(), le2.getText());
                            resultado=tfe1.getText()+"-"+tfe2.getText();
                            controlador.resultadoPartido(null, resultado, true);
                        }
                }
            controlador.JDInfo(this, true, "Resultado introducido correctamente");
            limpiar();
        }catch (ResultadoPartido e){
            controlador.JDError(this, true, "Ese partido ya ha sido modificado");
            limpiar();
        }
        catch (Exception e){
            System.out.println("Problemas puntuacion");
        }         
    }//GEN-LAST:event_jButton1ActionPerformed

    public void limpiar(){
        tfe1.setText("");
        tfe2.setText("");
    }
    public boolean validar(){
        if(cbLiga.getSelectedIndex()==0&&cbJornadas.getSelectedIndex()==0&&cbPartidos.getSelectedIndex()==0)
            return false;        
        if(!digito(tfe1.getText()))
            return false;
        else 
            if(!digito(tfe2.getText()))
                return false;
        return true;
    }
    public boolean digito(String e){
        for (int c=0;c<e.length();c++)
            if(!Character.isDigit(e.charAt(c)))
                return false;
        return true;
    }
    public void initIcon(){
        try{
            Image i = ImageIO.read(getClass().getResource("/Views/recursos/logo_u_favicon.png"));
            setIconImage(i);
        }catch (IOException e){
            System.out.println("Problemas con el icono");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPuntos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbJornadas;
    private javax.swing.JComboBox<String> cbLiga;
    private javax.swing.JComboBox<String> cbPartidos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel le1;
    private javax.swing.JLabel le2;
    private javax.swing.JTextField tfe1;
    private javax.swing.JTextField tfe2;
    // End of variables declaration//GEN-END:variables
}
