/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.VPrincipal;

import control.controlador;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class VPrincipal extends javax.swing.JFrame {
    static boolean modoayuda = controlador.modoayuda;
    /**
     * Creates new form VPrincipal
     */
    public VPrincipal(){
        initComponents();
        inicializarVentana();
        TextoAyuda.setText(" ");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        HacerLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HacerLogin1 = new javax.swing.JLabel();
        HacerLogin2 = new javax.swing.JLabel();
        HacerLogin3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ayuda = new javax.swing.JLabel();
        TextoAyuda = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuOpciones = new javax.swing.JMenu();
        MenuLogin = new javax.swing.JMenuItem();
        jmCr = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmHerramientas = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem21 = new javax.swing.JMenuItem();
        jmPuntuacion = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        HacerLogin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        HacerLogin.setForeground(new java.awt.Color(255, 0, 0));
        HacerLogin.setText("Por favor, inicie sesión. Opciones>>Login.");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/VPrincipal/Logo_grande.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bienvenido/a al gestor de e-sports");

        HacerLogin1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        HacerLogin1.setForeground(new java.awt.Color(255, 0, 0));
        HacerLogin1.setText("o");

        HacerLogin2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        HacerLogin2.setForeground(new java.awt.Color(255, 0, 0));
        HacerLogin2.setText("haz click");

        HacerLogin3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        HacerLogin3.setForeground(new java.awt.Color(0, 0, 255));
        HacerLogin3.setText("aquí");
        HacerLogin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HacerLogin3MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/VPrincipal/Gif.gif"))); // NOI18N

        Ayuda.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        Ayuda.setForeground(new java.awt.Color(0, 0, 0));
        Ayuda.setText("Ayuda (?)");
        Ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AyudaMouseClicked(evt);
            }
        });

        TextoAyuda.setText("Texto ayuda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(HacerLogin1)
                                .addGap(184, 184, 184))
                            .addComponent(HacerLogin)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(HacerLogin2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HacerLogin3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(580, 580, 580)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Ayuda)))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextoAyuda)
                    .addComponent(jLabel3))
                .addGap(194, 194, 194))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(HacerLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HacerLogin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HacerLogin3)
                    .addComponent(HacerLogin2))
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(TextoAyuda)
                .addGap(15, 15, 15)
                .addComponent(Ayuda)
                .addGap(385, 385, 385))
        );

        MenuOpciones.setText("Opciones");
        MenuOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuOpcionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuOpcionesMouseExited(evt);
            }
        });

        MenuLogin.setText("Login");
        MenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLoginActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuLogin);

        jmCr.setText("Cerrar sesión");
        MenuOpciones.add(jmCr);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuOpciones.add(jMenuItem2);

        jMenuBar1.add(MenuOpciones);

        jmHerramientas.setText("Herramientas");

        jMenu2.setText("Registrar");

        jMenuItem3.setText("Usuario");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Jugador");
        jMenuItem4.setToolTipText("");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Dueño");
        jMenu2.add(jMenuItem5);

        jMenuItem10.setText("Equipo");
        jMenu2.add(jMenuItem10);
        jMenu2.add(jSeparator1);

        jMenuItem9.setText("Liga");
        jMenu2.add(jMenuItem9);
        jMenu2.add(jSeparator2);

        jMenuItem6.setText("Aministrador");
        jMenu2.add(jMenuItem6);

        jmHerramientas.add(jMenu2);

        jMenu3.setText("Modificar");

        jMenuItem11.setText("Usuario");
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Jugador");
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("Dueño");
        jMenu3.add(jMenuItem13);

        jMenuItem7.setText("Equipo");
        jMenu3.add(jMenuItem7);

        jmHerramientas.add(jMenu3);

        jMenu4.setText("Eliminar");

        jMenuItem8.setText("Usuario");
        jMenu4.add(jMenuItem8);

        jMenuItem14.setText("Jugador");
        jMenu4.add(jMenuItem14);

        jMenuItem15.setText("Dueño");
        jMenu4.add(jMenuItem15);

        jMenuItem16.setText("Equipo");
        jMenu4.add(jMenuItem16);

        jmHerramientas.add(jMenu4);

        jMenu5.setText("Listar");

        jMenuItem17.setText("Usuarios");
        jMenu5.add(jMenuItem17);

        jMenuItem18.setText("Jugadores");
        jMenu5.add(jMenuItem18);

        jMenuItem19.setText("Dueños");
        jMenuItem19.setToolTipText("");
        jMenu5.add(jMenuItem19);

        jMenuItem20.setText("Equipos");
        jMenu5.add(jMenuItem20);
        jMenu5.add(jSeparator4);

        jMenuItem22.setText("Ligas");
        jMenu5.add(jMenuItem22);

        jMenuItem23.setText("Partidos");
        jMenu5.add(jMenuItem23);

        jMenuItem24.setText("Jornadas");
        jMenu5.add(jMenuItem24);
        jMenu5.add(jSeparator3);

        jMenuItem21.setText("Administradores");
        jMenu5.add(jMenuItem21);

        jmHerramientas.add(jMenu5);

        jMenuBar1.add(jmHerramientas);

        jmPuntuacion.setText("Gestión de puntuación");
        jMenuBar1.add(jmPuntuacion);

        jMenu7.setText("Resultados y datos");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu7MouseExited(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLoginActionPerformed
        //Funcion que abre la ventana login
        control.controlador.toVLogin();
    }//GEN-LAST:event_MenuLoginActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Cuando se abre la ventana 
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        controlador.JDError(this, true, "Error de retraso", "Porque alejandro es tontito");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void HacerLogin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HacerLogin3MouseClicked
        
    }//GEN-LAST:event_HacerLogin3MouseClicked

    private void AyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AyudaMouseClicked
        //Muestra la caja de ayuda o la oculta si se desactiva la ayuda
        if (modoayuda == false) { 
            modoayuda = true;
            Ayuda.setText("Cerrar ayuda");
            JOptionPane.showMessageDialog(null, "Modo ayuda activado, sitúa el ratón sobre las opciones que quieras saber qué hacen");
        }else{
            modoayuda = false;
            Ayuda.setText("Ayuda (?)");
        }
        System.out.println("Modo ayuda: " + modoayuda);
    }//GEN-LAST:event_AyudaMouseClicked

    private void MenuOpcionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuOpcionesMouseEntered
        //Ayuda opciones
        TextoAyuda.setText("Aquí podrás hacer login, cerrar sesión o salir de la app");
    }//GEN-LAST:event_MenuOpcionesMouseEntered

    private void MenuOpcionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuOpcionesMouseExited
        //Borra ayuda de opciones
        TextoAyuda.setText(" ");
    }//GEN-LAST:event_MenuOpcionesMouseExited

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //Cerrar todo
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseEntered
        //Ayuda resultados
        TextoAyuda.setText("Aquí podrás consultar resultados de partidos y ver futuros partidos en detalle");
    }//GEN-LAST:event_jMenu7MouseEntered

    private void jMenu7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseExited
        //Borra ayuda de resultados
        TextoAyuda.setText(" ");
    }//GEN-LAST:event_jMenu7MouseExited
    
    public void inicializarVentana(){
        
        setLocationRelativeTo(null);
        TextoAyuda.setText(" ");
        jmCr.setVisible(false);
        jmHerramientas.setVisible(false);
        jmPuntuacion.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ayuda;
    private javax.swing.JLabel HacerLogin;
    private javax.swing.JLabel HacerLogin1;
    private javax.swing.JLabel HacerLogin2;
    private javax.swing.JLabel HacerLogin3;
    private javax.swing.JMenuItem MenuLogin;
    private javax.swing.JMenu MenuOpciones;
    private javax.swing.JLabel TextoAyuda;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem jmCr;
    private javax.swing.JMenu jmHerramientas;
    private javax.swing.JMenu jmPuntuacion;
    // End of variables declaration//GEN-END:variables
}
